//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Restricted_AuthenticatedUsersOnly_Default {
    
    /// <summary>
    /// TestUserIsAuthenticatedMethodResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label TestUserIsAuthenticatedMethodResult;
    
    /// <summary>
    /// TestUsersRoleMethodResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label TestUsersRoleMethodResult;
    
    /// <summary>
    /// TestAdministratorsRoleMethodResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label TestAdministratorsRoleMethodResult;
    
    /// <summary>
    /// TestUsersOrAdministratorsRoleMethodResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label TestUsersOrAdministratorsRoleMethodResult;
    
    /// <summary>
    /// TestUserIsBobMethodResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label TestUserIsBobMethodResult;
}
